config/routes.rb
Rails.application.routes.draw do
  resources :secret_codes, only: [:index] do
    collection do
      get :generate
    end
  end
  devise_for :users, controllers: {registrations: 'users/registrations'}
  root 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord

  has_many :user_roles
  has_many :users, through: :user_roles

end

app/models/secret_code.rb
class SecretCode < ApplicationRecord
  # Associations
  belongs_to :user, optional: true

  # Delegators
  delegate :email, to: :user, prefix: 'user', allow_nil: true

  # Scopes
  scope :unrelated, -> { where(user_id: nil) }

  # Callbacks
  before_create :set_code_string, unless: :code_string?

  # def find_ptype
  #   -> (column, formated_value) { 
  #     # where("position_positions.data->>'ptype' = ?", "%#{formated_value}%")
  #     where("payload->>'kind' = ?", "%#{formated_value}%")
  #   }
  # end

  scope :find_ptype, ->(column, formated_value){ 
    where("payload->>'kind' LIKE ?", "%#{formated_value}%")
  }

  private

  def set_code_string
    self.code_string = SecureRandom.uuid
  end

end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :selected_secret_code

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Validations
  # validates :selected_secret_code, presence: true
  validates_presence_of :type, on: :update

  # Associations
  has_one :secret_code
  has_many :user_roles
  has_many :roles, through: :user_roles

  # Callbacks
  before_create :assign_secret_code
  after_initialize :set_roles
  
  private

  def assign_secret_code
    self.secret_code = SecretCode.find(selected_secret_code)
  end

  def set_roles
    class << self
      Role.find_each do |role|
        define_method("#{role.role_name}?".to_sym){
          roles.include?(role)
        }
      end
    end
  end

end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end
end

app/controllers/secret_codes_controller.rb
class SecretCodesController < ApplicationController
  # GET /secret_codes
  def index
    authorize! :read, nil
    @secret_codes = SecretCode.all
  end

  # Custom action to generate bulk secret codes
  def generate
    message = 'Secret codes generated successfully.'
    begin
      ApplicationRecord.transaction do
        generate_params[:limit].to_i.times do
          SecretCode.new.save!
        end
      end
    rescue => exception
      message = exception.message
    end
    redirect_to secret_codes_path, notice: message
  end


  private
    def generate_params
      params.require(:secret_code).permit(:limit)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:selected_secret_code, :first, :last])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def pagination_config
    [1, 10, 20, 50, 100].collect{|k| [k, k]}
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/secret_codes_helper.rb
module SecretCodesHelper
end

app/views/application/_header.html.erb
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="<%= secret_codes_path %>">Secret Codes</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="<%= root_path %>">Home</a>
  </li>
  <% unless signed_in? %>
    <li class="nav-item">
      <a class="nav-link" href="<%= new_user_registration_path %>">Sign Up</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= new_user_session_path %>">Sign In</a>
    </li>
  <% else %>
    <li class="nav-item">
      <a class="nav-link" href="<%= destroy_user_session_path %>">Sign Out</a>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render partial: 'application/header'%>
      <% if notice %>
        <p class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/secret_codes/_form.html.erb
<%= form_with(model: secret_code, local: true) do |form| %>
  <% if secret_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(secret_code.errors.count, "error") %> prohibited this secret_code from being saved:</h2>

      <ul>
      <% secret_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :secret_code_user_id %>
  </div>

  <div class="field">
    <%= form.label :code_string %>
    <%= form.text_field :code_string, id: :secret_code_code_string %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/secret_codes/edit.html.erb
<h1>Editing Secret Code</h1>

<%= render 'form', secret_code: @secret_code %>

<%= link_to 'Show', @secret_code %> |
<%= link_to 'Back', secret_codes_path %>

app/views/secret_codes/index.html.erb
<h1>Secret Codes</h1>

<%if @secret_codes.exists? %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Email</th>
        <th>Code String</th>
      </tr>
    </thead>
    <tbody>
      <% @secret_codes.each do |secret_code| %>
        <tr>
          <td><%= secret_code.user_email %></td>
          <td><%= secret_code.code_string %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info">
    <strong>Info!</strong> Secret Codes not found.
  </div>
<% end %>

<h1>Generate Secret Codes</h1>
<%= form_for :secret_code, url: generate_secret_codes_path, method: :get do |f|%>
  <div class="col-md-3">
    <div class="form-group">
      <label>Select:</label>
      <%= f.select :limit, options_for_select(pagination_config, "10"), {}, {class: 'form-control'} %>
    </div>
    <div class="form-group">
    <%= f.submit "Generate", class: 'btn btn-success' %>
  </div>
  </div>
<% end %>

app/views/secret_codes/new.html.erb
<h1>New Secret Code</h1>

<%= render 'form', secret_code: @secret_code %>

<%= link_to 'Back', secret_codes_path %>

app/views/secret_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @secret_code.user_id %>
</p>

<p>
  <strong>Code string:</strong>
  <%= @secret_code.code_string %>
</p>

<%= link_to 'Edit', edit_secret_code_path(@secret_code) %> |
<%= link_to 'Back', secret_codes_path %>